apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-cluster-base.yaml
  - 02-operators.yaml
  - 03-monitoring.yaml
  - 04-storage.yaml
  - 05-vault.yaml
  - 06-oauth.yaml
  - 07-vault-eso-config.yaml
  - 08-external-secrets.yaml
  - 09-aap.yaml
  - 10-certificates.yaml
  - 11-portal.yaml
