apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

# Portal is deployed via Helm (see bootstrap script)
# portal-values.yaml is used with:
#   helm install rhaap-portal openshift-helm-charts/redhat-rhaap-portal \
#     --namespace aap-portal -f portal-values.yaml
